const menu = [
    {
        id: 1,
        name: "Dashboard",
        icon: "home",
        group: "Dashboard",
        route: "/",
        code: 701,
        isActive: false,
    },
    {
        id: 12,
        name: "Rapport",
        icon: "ballot",
        group: "Rapport",
        route: "/report",
        code: 701,
        isActive: false,
    },
    {
        id: 10,
        name: "Betalingen",
        icon: "cash-usd",
        group: "Betalingen",
        route: "/payments",
        code: 901,
        isActive: false,
    },
    {
        id: 2,
        name: "Bestellingen",
        icon: "clipboard-edit-outline",
        group: "Bestellingen",
        route: "/orders",
        code: 601,
        isActive: false,
    },
    {
        id: 3,
        name: "Historiek",
        icon: "history",
        group: "Historiek",
        route: "/orders/history",
        code: 604,
        isActive: false,
    },
    {
        id: 4,
        name: "Producten",
        icon: "food-fork-drink",
        group: "Producten",
        route: "/products",
        code: 501,
        isActive: false,
    },
    {
        id: 5,
        name: "Menu",
        icon: "format-list-bulleted-square",
        group: "Menu",
        route: "/menu",
        code: 401,
        isActive: false,
    },
    {
        id: 6,
        name: "Personeel",
        icon: "account-supervisor",
        group: "Personeel",
        route: "/staff",
        code: 301,
        isActive: false,
    },
    {
        id: 7,
        name: "Tafels",
        icon: "table-chair",
        group: "Tafels",
        route: "/tables",
        code: 201,
        isActive: false,
    },
    {
        id: 8,
        name: "QR-code",
        icon: "qrcode",
        group: "Qrcode",
        route: "/qrcode",
        code: 801,
        isActive: false,
    },
    {
        id: 9,
        name: "Mijn gegevens",
        icon: "card-account-details",
        group: "Mijn gegevens",
        route: "/details",
        code: 101,
        isActive: false
    },
    {
        id: 11,
        name: "Instellingen",
        icon: "cog",
        group: "Instellingen",
        route: "/settings",
        code: 1001,
        isActive: false
    },
    {
        id: 14,
        name: "Privacybeleid",
        icon: "police-badge",
        group: "Privacy",
        route: "/privacy",
        code: 2000,
        isActive: false
    }
]

export default menu;